-- Dummy data for populating database
INSERT INTO users (first_name, last_name, username, _password, email, points)
VALUES ('Ana', 'Janković', 'anaj', 'Lozinka123#', 'ana.jankovic@gmail.com', 20),
       ('Marko', 'Nikolić', 'marko_n', 'Lozinka456&', 'marko.nikolic@gmail.com', 28),
       ('Jelena', 'Petrović', 'jelena_p', 'Lozinka789*', 'jelena.petrovic@gmail.com', 37),
       ('Ivan', 'Kovačević', 'ivank', 'LozinkaAbc!', 'ivan.kovacevic@gmail.com', 14),
       ('Nikola', 'Stanković', 'nikola_s', 'Sifra123#', 'nikola.stankovic@gmail.com', 30),
       ('Milica', 'Simić', 'milica_s', 'Sifra456&', 'milica.simic@gmail.com', 20),
       ('Luka', 'Milić', 'luka_m', 'Sifra789*', 'luka.milic@gmail.com', 42),
       ('Tijana', 'Gajić', 'tijana_g', 'SifraAbc!', 'tijana.gajic@gmail.com', 15),
       ('Stefan', 'Dimitrijević', 'stefan_d', 'Pass123#', 'stefan.dimitrijevic@gmail.com', 39),
       ('Maja', 'Jović', 'maja_j', 'Pass456&', 'maja.jovic@gmail.com', 21),
       ('Aleksandar', 'Pavlović', 'aleksandar_p', 'Pass789*', 'aleksandar.pavlovic@gmail.com', 42),
       ('Dunja', 'Milovanović', 'dunja_m', 'PassAbc!', 'dunja.milovanovic@gmail.com', 20),
       ('Filip', 'Ristić', 'filip_r', 'Lozinka123#', 'filip.ristic@gmail.com', 32),
       ('Jovana', 'Lukić', 'jovana_l', 'Lozinka456&', 'jovana.lukic@gmail.com', 27),
       ('Nenad', 'Ilić', 'nenad_i', 'Lozinka789*', 'nenad.ilic@gmail.com', 13),
       ('Sara', 'Petrovic', 'sara_p', 'Pass123#', 'sara.petrovic@gmail.com', 10),
       ('Petar', 'Simic', 'petar_s', 'Pass456&', 'petar.simic@gmail.com', 8),
       ('Dusan', 'Stankovic', 'dusan_s', 'Pass789*', 'dusan.stankovic@gmail.com', 15),
       ('Katarina', 'Milic', 'katarina_m', 'PassAbc!', 'katarina.milic@gmail.com', 22),
       ('Admin', 'Admin', 'admin', 'admin123', 'admin@gmail.com', 0);
